
services:

  backend:
    build: .
    container_name: floatflow_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/floatflow_db
      SPRING_DATASOURCE_USERNAME: floatflow_user
      SPRING_DATASOURCE_PASSWORD: floatflow_password
      SPRING_THREADS_VIRTUAL_ENABLED: "true"

  postgres:
    image: postgres:15
    container_name: floatflow_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: floatflow_db
      POSTGRES_USER: floatflow_user
      POSTGRES_PASSWORD: floatflow_password
    ports:
      - "5432:5432"
    volumes:
      - floatflow_pgdata:/var/lib/postgresql/data

volumes:
  floatflow_pgdata:
    driver: local